language: node_js
os:
  - linux
cache: yarn
before_script:
  - npm install -g gatsby-cli gh-pages
node_js:
  - "12"
script:
  - yarn install && node ./script/sync-packages.js
  - echo "skipping tests"
deploy:
  provider: script
  script: yarn install && yarn build && gh-pages -d public -r https://$GH_TOKEN@github.com/XYShaoKang/gatsby-getting-started.git
  on:
    branch: master
